# Name of the Workflow
name: My Test Workflow

# Define the trigger events
on: [push]

# Jobs run in parallel by default
jobs:
    say-hello:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello, Github Action!"
    
    build-and-test:
        # Jobs to build and test C code
        needs: [say-hello]
        runs-on: ubuntu-latest
        steps:
            # Use github.com/actions/checkout to checkout this repo
            - name: Checkout this repo
              uses: actions/checkout@v3

            # Install necessary packages
            - name: Install dependencies
              run: sudo apt install -y build-essential python3

            # See where we are
            - run: pwd

            # Run the test
            - name: Run test
              run: python3 test.py

    